// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 23 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "headers/vulkan.h"
#include "headers/vulkan_beta.h"
#include "vk_wrapper.h"
#include "vk_bridge.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// PFN_vkDebugReportCallbackEXT_c918aac4 is a proxy for callback PFN_vkDebugReportCallbackEXT.
unsigned int PFN_vkDebugReportCallbackEXT_c918aac4(unsigned int flags, VkDebugReportObjectTypeEXT objectType, unsigned long int object, unsigned long int location, int messageCode, char* pLayerPrefix, char* pMessage, void* pUserData);

// PFN_vkDeviceMemoryReportCallbackEXT_e34d104c is a proxy for callback PFN_vkDeviceMemoryReportCallbackEXT.
void PFN_vkDeviceMemoryReportCallbackEXT_e34d104c(VkDeviceMemoryReportCallbackDataEXT* pCallbackData, void* pUserData);

