// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 20 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vulkan provides Go bindings for vulkan.h
*/
package vulkan
