VULKAN_HEADERS_URL=https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v1.3.240.zip

help:
	@echo "Available targets:"
	@echo "  help          - show this help"
	@echo "  run           - execute full pipeline: download, patch-headers, generate, patch-go, test"
	@echo "  download      - download Vulkan headers ZIP and extract *.h into ./vulkan"
	@echo "  patch-headers - apply local patches to downloaded Vulkan headers (comments H264 and H265 stuff)"
	@echo "  install-tool  - install c-for-go generator tool"
	@echo "  generate      - generate bindings from vulkan.yml"
	@echo "  patch-go      - apply post-generation patch to const.go (fix true/false type)"
	@echo "  clean         - remove generated Go/C helper files"
	@echo "  test          - build project to verify compilation"
	@echo "  release       - regenerate version.go metadata"

run: download patch-headers generate patch-go test

download:
	curl -L -O $(VULKAN_HEADERS_URL)
	unzip -j -o $(notdir $(VULKAN_HEADERS_URL)) 'Vulkan-Headers-*/include/vulkan/*.h' -d ./vulkan

patch-headers:
	patch -N -d vulkan -p0 < vulkan/vulkan_core_h.patch
	patch -N -d vulkan -p0 < vulkan/vulkan_beta_h.patch

install-tool:
	go install github.com/xlab/c-for-go@latest

generate:
	c-for-go -ccdefs vulkan.yml

patch-go:
	patch -N -p0 < const_go.patch

clean:
	rm vulkan.go doc.go types.go const.go
	rm cgo_helpers.go cgo_helpers.c cgo_helpers.h

test:
	go build

# NOTE: MUST update version number here prior to running 'make release'
VERS=v1.0.9
PACKAGE=vulkan
GIT_COMMIT=`git rev-parse --short HEAD`
VERS_DATE=`date -u +%Y-%m-%d\ %H:%M`
VERS_FILE=version.go

release:
	@echo "// WARNING: auto-generated by Makefile release target -- run 'make release' to update" > $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	@echo "package $(PACKAGE)" >> $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	@echo "const (" >> $(VERS_FILE)
	@echo "	GoVersion     = \"$(VERS)\"" >> $(VERS_FILE)
	@echo "	GitCommit   = \"$(GIT_COMMIT)\" // the commit JUST BEFORE the release" >> $(VERS_FILE)
	@echo "	VersionDate = \"$(VERS_DATE)\" // UTC" >> $(VERS_FILE)
	@echo ")" >> $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	/bin/cat $(VERS_FILE)
