// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vulkan

const (
	GoVersion     = "v1.0.9"
	GitCommit   = "713fb68" // the commit JUST BEFORE the release
	VersionDate = "2026-03-02 15:16" // UTC
)

