// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vulkan

const (
	GoVersion   = "v1.0.7"
	GitCommit   = "8a345fd"          // the commit JUST BEFORE the release
	VersionDate = "2023-10-07 02:17" // UTC
)
