// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vulkan

const (
	GoVersion   = "v1.0.8"
	GitCommit   = "6baec6f"          // the commit JUST BEFORE the release
	VersionDate = "2024-07-20 18:47" // UTC
)
